# Generated by Django 5.1.4 on 2024-12-14 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Task')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Details')),
                ('task_date', models.DateTimeField(auto_now=True, verbose_name='Date of Creation')),
                ('is_done', models.BooleanField(default=False, verbose_name='Done')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.category', verbose_name='Categories')),
            ],
        ),
    ]
